export const INITIAL_SLAYERS = [
  {
    id: "slayer-1",
    name: "Tanjiro Kamado",
    japaneseName: "竈門 炭治郎",
    breathingStyle: "Sun & Water Breathing",
    baseBreathing: "Water",
    rank: "Kanoe",
    rankLevel: 7,
    preferredRole: "Vanguard",
    skills: ["Total Concentration Constant", "Heightened Olfactory Sense", "Dance of the Fire God", "Dragon Sun Halo Head Dance"],
    interests: ["Demon Rehabilitation", "Swordsmithing Lore", "Family Protection", "Culinary Arts"],
    combatPower: 89,
    katanaColor: "Jet Black",
    avatar: "🌊",
    assignedTeamId: null
  },
  {
    id: "slayer-2",
    name: "Zenitsu Agatsuma",
    japaneseName: "我妻 善逸",
    breathingStyle: "Thunder Breathing (雷の呼吸)",
    baseBreathing: "Thunder",
    rank: "Kanoe",
    rankLevel: 6,
    preferredRole: "Recon",
    skills: ["Thunderclap and Flash: Godspeed (霹靂一閃 神速)", "Heightened Auditory Sense", "Sixfold Dash", "Flaming Thunder God (火雷神)"],
    interests: ["Nezuko-chan", "Homing Pigeons", "Sweets & Wagashi", "Safe Patrols"],
    combatPower: 86,
    katanaColor: "Golden Yellow Lightning",
    avatar: "⚡",
    avatarImage: "/images/zenitsu.png",
    assignedTeamId: null
  },
  {
    id: "slayer-3",
    name: "Inosuke Hashibira",
    japaneseName: "嘴平 伊之助",
    breathingStyle: "Beast Breathing",
    baseBreathing: "Wind",
    rank: "Kanoe",
    rankLevel: 6,
    preferredRole: "Vanguard",
    skills: ["Spatial Awareness", "Dual Serrated Swords", "Joint Dislocation", "Rip and Tear"],
    interests: ["Mountain King Duels", "Tempura", "Headbutting Trees", "Boasting"],
    combatPower: 85,
    katanaColor: "Indigo Grey",
    avatar: "🐗",
    assignedTeamId: null
  },
  {
    id: "slayer-4",
    name: "Kanao Tsuyuri",
    japaneseName: "栗花落 カナヲ",
    breathingStyle: "Flower Breathing",
    baseBreathing: "Water",
    rank: "Tsuguko",
    rankLevel: 8,
    preferredRole: "Tactician",
    skills: ["Equinoctial Vermilion Eye", "Superhuman Kinetic Vision", "Crimson Hanagoromo", "Silent Step"],
    interests: ["Coin Flipping", "Butterfly Gardening", "Quiet Contemplation", "Aoi's Onigiri"],
    combatPower: 88,
    katanaColor: "Light Pink",
    avatar: "🌸",
    assignedTeamId: null
  },
  {
    id: "slayer-5",
    name: "Genya Shinazugawa",
    japaneseName: "不死川 玄弥",
    breathingStyle: "Demonic Assimilation & Gunner",
    baseBreathing: "Other",
    rank: "Kanoe",
    rankLevel: 6,
    preferredRole: "Trapper",
    skills: ["Demon Flesh Ingestion", "Double-Barrel Nichirin Shotgun", "Regeneration", "Flesh Bullets"],
    interests: ["Bonsai Cultivation", "Reconciling with Brother", "Weapon Modding", "Target Practice"],
    combatPower: 82,
    katanaColor: "Dark Purple & Gunmetal",
    avatar: "💥",
    assignedTeamId: null
  },
  {
    id: "slayer-6",
    name: "Aoi Kanzaki",
    japaneseName: "神崎 アオイ",
    breathingStyle: "Water Breathing (Medical Practitioner)",
    baseBreathing: "Water",
    rank: "Mizunoto",
    rankLevel: 4,
    preferredRole: "Medical",
    skills: ["Wisteria Medicine Alchemy", "Butterfly Ward Triage", "Rehabilitation Regimen", "Venom Antidote"],
    interests: ["Herbal Medicine", "Hygiene Management", "Baking Steamed Buns", "Slayer Physicals"],
    combatPower: 58,
    katanaColor: "Pale Blue",
    avatar: "💊",
    assignedTeamId: null
  },
  {
    id: "slayer-7",
    name: "Giyu Tomioka",
    japaneseName: "冨岡 義勇",
    breathingStyle: "Water Breathing (Water Hashira)",
    baseBreathing: "Water",
    rank: "Hashira",
    rankLevel: 10,
    preferredRole: "Vanguard",
    skills: ["Eleventh Form: Dead Calm (凪)", "Flowing Water Calamity", "Master Swordsmanship", "Total Concentration Constant"],
    interests: ["Simmered Salmon with Daikon", "Solitude", "Kasugai Crow Training", "Duty"],
    combatPower: 96,
    katanaColor: "Deep Ocean Blue",
    avatar: "🌊",
    assignedTeamId: null
  },
  {
    id: "slayer-8",
    name: "Shinobu Kocho",
    japaneseName: "胡蝶 しのぶ",
    breathingStyle: "Insect Breathing (Insect Hashira)",
    baseBreathing: "Water",
    rank: "Hashira",
    rankLevel: 10,
    preferredRole: "Medical",
    skills: ["Dance of the Bee Sting", "Wisteria Lethal Neurotoxin", "Super Speed Thrusts", "Compound Pharmacology"],
    interests: ["Ghost Stories", "Venom Synthesis", "Sisters Legacy", "Butterfly Rearing"],
    combatPower: 92,
    katanaColor: "Lavender & Turquoise",
    avatar: "🦋",
    assignedTeamId: null
  },
  {
    id: "slayer-9",
    name: "Kyojuro Rengoku",
    japaneseName: "煉獄 杏寿郎",
    breathingStyle: "Flame Breathing (Flame Hashira)",
    baseBreathing: "Flame",
    rank: "Hashira",
    rankLevel: 10,
    preferredRole: "Vanguard",
    skills: ["Ninth Form: Rengoku (煉獄)", "Blazing Universe", "Indomitable Spirit", "Rising Scorching Sun"],
    interests: ["Sweet Potato Rice", "Sumo Wrestling", "Mentoring Juniors", "Proclaiming 'UMAI!'"],
    combatPower: 97,
    katanaColor: "Crimson Flame",
    avatar: "🔥",
    assignedTeamId: null
  },
  {
    id: "slayer-10",
    name: "Tengen Uzui",
    japaneseName: "宇髄 天元",
    breathingStyle: "Sound Breathing (Sound Hashira)",
    baseBreathing: "Thunder",
    rank: "Hashira",
    rankLevel: 10,
    preferredRole: "Recon",
    skills: ["Musical Score Technique", "Dual Cleaver Explosive Bombs", "Shinobi Poison Resistance", "Flashy Stealth"],
    interests: ["Flamboyant Aesthetics", "Hot Springs", "Ninja Mice Training", "Fireworks"],
    combatPower: 94,
    katanaColor: "Amber & Black Notch",
    avatar: "🎆",
    assignedTeamId: null
  },
  {
    id: "slayer-11",
    name: "Muichiro Tokito",
    japaneseName: "時透 無一郎",
    breathingStyle: "Mist Breathing (Mist Hashira)",
    baseBreathing: "Wind",
    rank: "Hashira",
    rankLevel: 10,
    preferredRole: "Tactician",
    skills: ["Seventh Form: Obscuring Clouds (朧)", "Sea of Clouds and Haze", "Transparent World", "Prodigy Reflexes"],
    interests: ["Origami", "Cloud Watching", "Silent Meditation", "Bird Whittling"],
    combatPower: 95,
    katanaColor: "Mist White",
    avatar: "🌫️",
    assignedTeamId: null
  },
  {
    id: "slayer-12",
    name: "Mitsuri Kanroji",
    japaneseName: "甘露寺 蜜璃",
    breathingStyle: "Love Breathing (Love Hashira)",
    baseBreathing: "Flame",
    rank: "Hashira",
    rankLevel: 9,
    preferredRole: "Vanguard",
    skills: ["Whip-like Flexible Nichirin", "Catlegged Winds of Love", "Superdense Muscle Constitution", "Acrobatic Flurry"],
    interests: ["Sakura Mochi", "Western Western Cuisine", "Finding a Strong Husband", "Adopting Pets"],
    combatPower: 93,
    katanaColor: "Bright Hot Pink",
    avatar: "💖",
    assignedTeamId: null
  },
  {
    id: "slayer-13",
    name: "Murata",
    japaneseName: "村田",
    breathingStyle: "Water Breathing (Veteran Sentinel)",
    baseBreathing: "Water",
    rank: "Kanoe",
    rankLevel: 5,
    preferredRole: "Trapper",
    skills: ["Basic Water Forms", "Mount Natagumo Survival", "Signal Flare Dispatch", "Defensive Stance"],
    interests: ["Surviving the Night", "Hair Care", "Checking on Tanjiro", "Card Games"],
    combatPower: 65,
    katanaColor: "Standard Silver",
    avatar: "🛡️",
    assignedTeamId: null
  },
  {
    id: "slayer-14",
    name: "Gotou",
    japaneseName: "後藤",
    breathingStyle: "Kakushi Corps Brigade",
    baseBreathing: "Other",
    rank: "Mizunoto",
    rankLevel: 4,
    preferredRole: "Medical",
    skills: ["Battlefield Extraction", "Stretcher Transport", "Emergency Bandaging", "Clean-up Protocol"],
    interests: ["Castella Cakes", "Prompt Reporting", "Avoiding Hashira Wrath", "Inventory Logs"],
    combatPower: 52,
    katanaColor: "Unarmed Support",
    avatar: "🚑",
    assignedTeamId: null
  },
  {
    id: "slayer-15",
    name: "Gyomei Himejima",
    japaneseName: "悲鳴嶼 行冥",
    breathingStyle: "Stone Breathing (Stone Hashira)",
    baseBreathing: "Stone",
    rank: "Hashira",
    rankLevel: 10,
    preferredRole: "Vanguard",
    skills: ["Spiked Flail & Battleaxe Master", "Volcanic Rock Rapid Conquest", "Stone Sanctuary", "Echolocation Perception"],
    interests: ["Chanting Sutras", "Shakuhachi Flute", "Cats", "Crying for the Pure"],
    combatPower: 99,
    katanaColor: "Heavy Dark Iron",
    avatar: "🪨",
    assignedTeamId: null
  },
  {
    id: "slayer-16",
    name: "Sanemi Shinazugawa",
    japaneseName: "不死川 実弥",
    breathingStyle: "Wind Breathing (Wind Hashira)",
    baseBreathing: "Wind",
    rank: "Hashira",
    rankLevel: 10,
    preferredRole: "Vanguard",
    skills: ["Idaten Gale", "Claws-Purifying Wind", "Marechi Rare Blood Trap", "Relentless Slashing"],
    interests: ["Ohagi (Sweet Rice Cakes)", "Breeding Rhinoceros Beetles", "Brutal Sparring", "Protecting Genya secretly"],
    combatPower: 96,
    katanaColor: "Forest Green Serrated",
    avatar: "🌪️",
    assignedTeamId: null
  }
];

export const INITIAL_MISSIONS = [
  {
    id: "mission-1",
    title: "Mount Natagumo Web Cleansing",
    japaneseTitle: "那田蜘蛛山 索敵討伐",
    dangerRank: "Rank B",
    location: "Mount Natagumo Forest, Gunma",
    teamSize: 4,
    requiredRoles: ["Vanguard", "Medical"],
    preferredBreathing: ["Water", "Insect", "Wind"],
    requiredSkills: ["Total Concentration Constant", "Venom Antidote"],
    minCombatPower: 260,
    demonEncounter: "Rui & Spider Family (Lower Moon 5)",
    demonImage: "/images/rui.png",
    demonRankTitle: "Lower Moon 5 (下弦の伍)",
    description: "Entire squads of slayers have been turned into puppets by razor-sharp steel threads. Slayers must withstand acidic poison and cut the mother and daughter threads before confronting Rui.",
    assignedTeamId: null
  },
  {
    id: "mission-2",
    title: "Mugen Train Nightmare Evacuation",
    japaneseTitle: "無限列車 護衛追撃",
    dangerRank: "Rank A",
    location: "Locomotive Railway, Tokyo Outskirts",
    teamSize: 4,
    requiredRoles: ["Vanguard", "Tactician", "Recon"],
    preferredBreathing: ["Flame", "Thunder", "Sun"],
    requiredSkills: ["Heightened Auditory Sense", "High Speed Reflexes"],
    minCombatPower: 310,
    demonEncounter: "Enmu (Lower Moon 1) & Akaza Incursion (Upper Moon 3)",
    demonImage: "/images/enmu.png",
    secondaryDemonImage: "/images/akaza.png",
    demonRankTitle: "Lower Moon 1 (下弦の壱) & Upper Moon 3",
    description: "Over 200 civilian passengers are trapped inside an 8-car demonic train merged with Enmu's flesh. Requires simultaneous defense of passengers and synchronized decapitation.",
    assignedTeamId: null
  },
  {
    id: "mission-3",
    title: "Yoshiwara Entertainment District Infiltration",
    japaneseTitle: "吉原遊郭 潜入暗殺",
    dangerRank: "Rank S",
    location: "Yoshiwara Red-Light District, Tokyo",
    teamSize: 4,
    requiredRoles: ["Recon", "Vanguard", "Trapper"],
    preferredBreathing: ["Sound", "Beast", "Flower"],
    requiredSkills: ["Spatial Awareness", "Shinobi Poison Resistance"],
    minCombatPower: 340,
    demonEncounter: "Daki & Gyutaro (Upper Moon 6 Dual Threats)",
    demonImage: "/images/gyutaro.png",
    secondaryDemonImage: "/images/daki.png",
    demonRankTitle: "Upper Moon 6 (上弦の陸)",
    description: "Oiran courtesans are vanishing through blood sashes. Slayers must conduct covert recon, resist blood sickle lethal venom, and sever both siblings' necks simultaneously.",
    assignedTeamId: null
  },
  {
    id: "mission-4",
    title: "Swordsmith Village Emergency Defense",
    japaneseTitle: "刀鍛冶の里 防衛奇襲",
    dangerRank: "Rank S",
    location: "Hidden Sanctuary of the Swordsmiths",
    teamSize: 4,
    requiredRoles: ["Tactician", "Vanguard", "Medical"],
    preferredBreathing: ["Mist", "Love", "Stone"],
    requiredSkills: ["Transparent World", "Wisteria Medicine Alchemy"],
    minCombatPower: 350,
    demonEncounter: "Gyokko (Upper Moon 5) & Hantengu (Upper Moon 4)",
    demonImage: "/images/gyokko.png",
    secondaryDemonImage: "/images/hantengu.png",
    demonRankTitle: "Upper Moon 5 & 4 (上弦の伍・肆)",
    description: "The secret village that crafts Nichirin katanas is under surprise siege by grotesque fish pots and splitting emotional clones. The forge and master smiths must be preserved at all costs.",
    assignedTeamId: null
  },
  {
    id: "mission-5",
    title: "Tsuzumi Drum Mansion Search & Rescue",
    japaneseTitle: "鼓の屋敷 空間突破",
    dangerRank: "Rank C",
    location: "Deep Mountain Mansion, Tochigi",
    teamSize: 3,
    requiredRoles: ["Vanguard", "Recon"],
    preferredBreathing: ["Water", "Thunder"],
    requiredSkills: ["Heightened Olfactory Sense"],
    minCombatPower: 190,
    demonEncounter: "Kyogai (Former Lower Moon 6 - Drum Demon)",
    demonImage: "/images/kyogai.png",
    demonRankTitle: "Former Lower Moon 6 (元下弦の陸)",
    description: "A mansion where rooms rotate 90 degrees with every drum beat. Slayers must adapt to disorienting gravity shifts and rescue trapped civilians with Marechi blood.",
    assignedTeamId: null
  },
  {
    id: "mission-6",
    title: "Asakusa City Moonlit Shadows Patrol",
    japaneseTitle: "浅草市街 密偵巡回",
    dangerRank: "Rank D",
    location: "Asakusa Metropolis, Tokyo",
    teamSize: 3,
    requiredRoles: ["Recon", "Tactician"],
    preferredBreathing: ["Water", "Flower"],
    requiredSkills: ["Total Concentration Constant"],
    minCombatPower: 160,
    demonEncounter: "Susamaru (Temari Demon) & Yahaba (Arrow Demon)",
    demonImage: "/images/susamaru.png",
    secondaryDemonImage: "/images/yahaba.png",
    demonRankTitle: "Blood Demon Art Duo (異能の鬼)",
    description: "Urban patrol in the bustling metropolis of Asakusa. Watch for invisible directional vector arrows and exploding temari balls while minimizing civilian notice.",
    assignedTeamId: null
  },
  {
    id: "mission-7",
    title: "Infinity Castle Decapitation Raid",
    japaneseTitle: "無限城 上弦討伐決戦",
    dangerRank: "Rank S",
    location: "Dimensional Fortress Infinity Castle",
    teamSize: 4,
    requiredRoles: ["Vanguard", "Tactician", "Medical"],
    preferredBreathing: ["Moon", "Sun", "Stone", "Wind"],
    requiredSkills: ["Transparent World", "Selfless State"],
    minCombatPower: 380,
    demonEncounter: "Kokushibo (Upper Moon 1) & Doma (Upper Moon 2)",
    demonImage: "/images/kokushibo.png",
    secondaryDemonImage: "/images/doma.png",
    demonRankTitle: "Upper Moon 1 & 2 (上弦の壱・弐)",
    description: "The supreme incursion within the labyrinthine shifting corridors of the Infinity Castle against the deadliest Upper Moons.",
    assignedTeamId: null
  }
];

export const TWELVE_KIZUKI_RANKINGS = [
  {
    id: "kizuki-1",
    name: "Kokushibo",
    japaneseName: "黒死牟",
    rankCategory: "Upper Moon (上弦)",
    rankTitle: "Upper Moon 1 (上弦の壱)",
    dangerRank: "Rank S",
    bloodDemonArt: "Moon Breathing & Flesh Katana (月の呼吸)",
    image: "/images/kokushibo.png",
    threatPower: 100,
    description: "The supreme leader of the Twelve Kizuki. A legendary former swordsman with six glowing eyes and a living blade constructed of demonic flesh.",
    counterHint: "Requires multiple Hashira marks, Transparent World, and Crimson Red Nichirin Blades."
  },
  {
    id: "kizuki-2",
    name: "Doma",
    japaneseName: "童磨",
    rankCategory: "Upper Moon (上弦)",
    rankTitle: "Upper Moon 2 (上弦の弐)",
    dangerRank: "Rank S",
    bloodDemonArt: "Cryokinesis & Frozen Lotus (粉凍りの氷)",
    image: "/images/doma.png",
    threatPower: 98,
    description: "Sociopathic cult leader of the Eternal Paradise. Wields golden fans that blast microscopic ice crystals to freeze and disintegrate the lungs.",
    counterHint: "Immunity to cold or massive lethal wisteria poison dosage."
  },
  {
    id: "kizuki-3",
    name: "Akaza",
    japaneseName: "猗窩座",
    rankCategory: "Upper Moon (上弦)",
    rankTitle: "Upper Moon 3 (上弦の参)",
    dangerRank: "Rank S",
    bloodDemonArt: "Destructive Death & Compass Needle (破壊殺 羅針)",
    image: "/images/akaza.png",
    threatPower: 96,
    description: "Unmatched martial arts prodigy whose Compass Needle locks onto the opponent's fighting spirit to predict every attack angle.",
    counterHint: "Suppressing all fighting spirit through the Selfless State (無我の境地)."
  },
  {
    id: "kizuki-4",
    name: "Hantengu",
    japaneseName: "半天狗",
    rankCategory: "Upper Moon (上弦)",
    rankTitle: "Upper Moon 4 (上弦の肆)",
    dangerRank: "Rank S",
    bloodDemonArt: "Emotion Division & Zohakuten Dragons (喜怒哀楽・憎魄天)",
    image: "/images/hantengu.png",
    threatPower: 94,
    description: "When decapitated, splits into emotional manifestations (Sekido, Karaku, Aizetsu, Urogi) and the colossal multi-headed Wood Dragon Zohakuten.",
    counterHint: "Hold back Zohakuten while a scout tracks the tiny heart demon hiding in the heart."
  },
  {
    id: "kizuki-5",
    name: "Gyokko",
    japaneseName: "玉壺",
    rankCategory: "Upper Moon (上弦)",
    rankTitle: "Upper Moon 5 (上弦の伍)",
    dangerRank: "Rank S",
    bloodDemonArt: "Porcelain Pots & Aquatic Hell (殺戮魚鱗)",
    image: "/images/gyokko.png",
    threatPower: 92,
    description: "Grotesque chimera demon dwelling inside porcelain pots, conjuring needle-firing demon fish and suffocating water prisons.",
    counterHint: "Mist Breathing obscuring forms and slicing pots at blinding godspeed."
  },
  {
    id: "kizuki-6",
    name: "Gyutaro & Daki",
    japaneseName: "妓夫太郎 & 堕姫",
    rankCategory: "Upper Moon (上弦)",
    rankTitle: "Upper Moon 6 (上弦の陸)",
    dangerRank: "Rank S",
    bloodDemonArt: "Poison Blood Sickles & Flesh Ribbons (飛血蝙 & 八重帯斬り)",
    image: "/images/gyutaro.png",
    secondaryImage: "/images/daki.png",
    threatPower: 90,
    description: "Sibling demon pair residing in Yoshiwara. Gyutaro's scythes carry instantaneous lethal venom, and both must be decapitated at the exact same instant.",
    counterHint: "Dual Vanguard simultaneous strike with high Shinobi poison resistance."
  },
  {
    id: "kizuki-7",
    name: "Enmu",
    japaneseName: "魘夢",
    rankCategory: "Lower Moon (下弦)",
    rankTitle: "Lower Moon 1 (下弦の壱)",
    dangerRank: "Rank A",
    bloodDemonArt: "Forced Dream Hypnosis (強制昏倒催眠の囁き)",
    image: "/images/enmu.png",
    threatPower: 84,
    description: "Sadistic dream manipulator who merged his bodily flesh with the 8-car Mugen Train to devour 200 sleeping passengers.",
    counterHint: "Severing one's own neck inside the dream to forcefully wake into reality."
  },
  {
    id: "kizuki-8",
    name: "Rui",
    japaneseName: "累",
    rankCategory: "Lower Moon (下弦)",
    rankTitle: "Lower Moon 5 (下弦の伍)",
    dangerRank: "Rank B",
    bloodDemonArt: "Steel Threads & Blood Weave (刻糸牢・殺目籠)",
    image: "/images/rui.png",
    threatPower: 76,
    description: "Spider demon ruler of Mount Natagumo. Spins razor-sharp crimson threads that can easily snap standard Nichirin steel katanas.",
    counterHint: "Water Breathing Eleventh Form 'Dead Calm' or concentrated Sun Breathing flare."
  },
  {
    id: "kizuki-9",
    name: "Kyogai",
    japaneseName: "響凱",
    rankCategory: "Former Kizuki (元下弦)",
    rankTitle: "Former Lower Moon 6 (元下弦の陸)",
    dangerRank: "Rank C",
    bloodDemonArt: "Tsuzumi Room Rotation (鼓の屋敷 空間転換)",
    image: "/images/kyogai.png",
    threatPower: 66,
    description: "Former Lower Moon whose body-embedded drums disorient enemies by flipping the mansion's rooms and firing air-slashing claws.",
    counterHint: "Spatial awareness and calculating gravity trajectories between drumbeats."
  },
  {
    id: "kizuki-10",
    name: "Susamaru & Yahaba",
    japaneseName: "朱紗丸 & 矢琶羽",
    rankCategory: "Blood Art Duo (異能の鬼)",
    rankTitle: "Asakusa Incursion Duo (浅草の刺客)",
    dangerRank: "Rank D",
    bloodDemonArt: "Destructive Temari & Vector Arrows (毬遊び・紅潔の矢)",
    image: "/images/susamaru.png",
    secondaryImage: "/images/yahaba.png",
    threatPower: 58,
    description: "Muzan's assassins who ambush in Asakusa. Susamaru hurls flesh-crushing temari balls guided by Yahaba's invisible vector arrows.",
    counterHint: "Yushiro's visual talismans and twisting water defensive circles."
  }
];
